### ISSUE TITLE
Missing check in RemoveSentReliableCommand.

### ISSUE THREAD

**Issue by juliolitwin** [moien007/NENet#3]
The function of RemoveSentReliableCommand is missing a check equal to the original. Is it on purpose? 

https://github.com/moien007/NENet/blob/c15bd79cc83eec6b797ac25b35c67f4b2136844b/src/NENet/ENetPeer.cs#L430

```
                    if (outgoingCommand.reliableSequenceNumber == reliableSequenceNumber &&
                        outgoingCommand.command.Header.ChannelID == channelID)
                        break;
```

ENet:
https://github.com/lsalzman/enet/blob/e3ada4ed750b976833e3d54a9c1179445289bbf6/protocol.c#L210

Cheers.

**Comment by moien007** [comment]
Thanks for the report, it's a mistake, can you make a PR?

**Comment by moien007** [comment]
I checked it again, and I realized that it is refactored that's why it looks different from the original code.
